### PR TITLE
Add support of optional meeting attendees

### PR DESCRIPTION
**Pull request by fatimazali**
Modify the earlier FindMeetingQuery function to check for optional meeting attendees and return availability for both optional and mandatory attendees if it is found.

### CODE REVIEW

**Comment by jessimb** [comment]
Do you mind merging the other two PRs first, so it's easier to see what's changed?

It's also totally possible merging won't actually help, lmk if that's the case.

**Comment by fatimazali** [comment]
Merged earlier two PRs

**Review by jessimb — COMMENTED** [review]
In general this LGTM, but I don't see any new tests for the new functionality?

**Comment by fatimazali** [comment]
Hmm, so the last PR #15 (https://github.com/fatimazali/step-2020/pull/15) contained the tests for optional attendees (the newer functionality). The tests for the older functionality (required attendees) were provided to us in the starter code--hope that answers your Q

**Review by jessimb — APPROVED** [review]
LGTM

**Pull request merged**
